---
- ros_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_topic_name: "/cmd_vel"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- gz_topic_name: "/imu/data_raw"
  gz_type_name: "gz.msgs.IMU"
  ros_topic_name: "/tlm/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS
- gz_topic_name: "/joint_states"
  gz_type_name: "gz.msgs.Model"
  ros_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  direction: GZ_TO_ROS
- gz_topic_name: "/odom"
  gz_type_name: "gz.msgs.Odometry"
  ros_topic_name: "/wheel_odom_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: GZ_TO_ROS
- gz_topic_name: "/oak/image_raw/points"
  gz_type_name: "gz.msgs.PointCloudPacked"
  ros_topic_name: "/oak/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  direction: GZ_TO_ROS
- gz_topic_name: "/oak/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  ros_topic_name: "/oak/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  direction: GZ_TO_ROS
- gz_topic_name: "/oak/image_raw"
  gz_type_name: "gz.msgs.Image"
  ros_topic_name: "/oak/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS
- gz_topic_name: "/pose_tf"
  gz_type_name: "gz.msgs.Pose_V"
  ros_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  direction: GZ_TO_ROS
- gz_topic_name: "/ground_truth_odom_cov"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  ros_topic_name: "/ground_truth_odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: GZ_TO_ROS