elevation_mapping:
  ros__parameters:
    postprocessor_pipeline: # set by postprocessor_pipeline_name

      filter1:
        name: buffer_normalizer
        type: gridMapFilters/BufferNormalizerFilter
        
      # Fill holes in the map with inpainting.
      filter2:
        name: inpaint
        type: gridMapCv/InpaintFilter
        params:
          input_layer: elevation
          output_layer: elevation_inpainted
          radius: 0.05

      # Smooth the inpainted map.
      filter3:
        name: mean_in_radius
        type: gridMapFilters/MeanInRadiusFilter
        params:
          input_layer: elevation_inpainted
          output_layer: elevation_smooth
          radius: 0.25

      # Compute Surface normals
      filter4:
        name: surface_normals
        type: gridMapFilters/NormalVectorsFilter
        params:
          input_layer: elevation_inpainted
          output_layers_prefix: normal_vectors_
          radius: 0.1
          normal_vector_positive_axis: z

      filter5:
        name: slope
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: slope
          expression: acos(normal_vectors_z)

      # Compute roughness as absolute difference from map to smoothened map.
      filter6:
        name: roughness
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: roughness
          expression: abs(elevation_inpainted - elevation_smooth)
      
      filter7:
        name: traversal_cost
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: traversal_cost
          expression: abs(slope)/0.29146

      filter8:
        # Set lower threshold on traversal_cost.
        name: lethal_traversal
        type: gridMapFilters/DuplicationFilter
        params:
          input_layer: traversal_cost
          output_layer: lethal_traversal
      
      filter9:
        # Set lower threshold on traversal_cost.
        name: lethal_traversal_threshold
        type: gridMapFilters/ThresholdFilter
        params:
          layer: lethal_traversal
          lower_threshold: 1.0
          set_to: 0.0
      
      # Smooth the inpainted map.
      filter10:
        name: traversal_cost_mean
        type: gridMapFilters/MeanInRadiusFilter
        params:
          input_layer: traversal_cost
          output_layer: traversal_cost_smooth
          radius: 0.5
      
      filter11:
        name: traversal_cost_final
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: traversal_cost_final
          expression: traversal_cost_smooth + lethal_traversal
      
      filter12:
        # Set upper threshold on traversal_cost.
        name: traversal_cost_upper_threshold
        type: gridMapFilters/ThresholdFilter
        params:
          layer: traversal_cost_final
          upper_threshold: 1.0
          set_to: 1.0
      
      
